@extends('layouts.app')

@section('title', 'Home')
@section('meta_description', 'Platform lengkap UKM untuk menguasai bahasa Jepang dari nol hingga mahir.')

@push('styles')
<link rel="stylesheet" href="{{ asset('css/carousel.css') }}">
@endpush

@section('content')

{{-- ======== HERO SECTION (dengan gambar kereta seperti original) ======== --}}
<section class="relative min-h-[85vh] flex items-center justify-center overflow-hidden">
    {{-- Background image kereta --}}
    <div class="absolute inset-0 z-0">
        <img src="{{ asset('images/hero_kereta.png') }}" alt="Hero kereta Jepang" class="w-full h-full object-cover" />
        <div class="absolute inset-0 bg-gradient-to-b from-white/70 via-white/50 to-white/80"></div>
    </div>

    {{-- Decorative elements --}}
    <div class="absolute top-10 left-10 text-8xl opacity-5 font-bold z-[1]" style="font-family: 'Noto Sans JP', sans-serif;">日</div>
    <div class="absolute bottom-10 right-10 text-9xl opacity-5 font-bold z-[1]" style="font-family: 'Noto Sans JP', sans-serif;">本</div>

    <div class="text-center px-4 relative z-10 max-w-3xl mx-auto">
        <p class="text-[#448646] text-lg md:text-xl mb-3 font-medium" style="font-family: 'Noto Sans JP', sans-serif;">
            日本語部へようこそ
        </p>
        <h1 class="text-4xl md:text-5xl lg:text-6xl font-extrabold text-[#296751] leading-tight mb-6">
            Belajar Bahasa &<br>
            <span class="bg-gradient-to-r from-[#448646] to-[#d6975e] bg-clip-text text-transparent">Budaya Jepang</span>
        </h1>
        <p class="text-gray-700 text-lg md:text-xl mb-10 max-w-xl mx-auto leading-relaxed">
            Platform lengkap UKM untuk menguasai bahasa Jepang dari nol hingga mahir.
        </p>
        <a href="#belajar"
           class="inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-[#448646] to-[#296751] text-white rounded-full text-lg font-semibold shadow-lg shadow-[#448646]/30 hover:shadow-xl hover:shadow-[#448646]/40 hover:-translate-y-1 transition-all duration-300">
            Lihat Materi
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
        </a>
    </div>
</section>

{{-- ======== GALLERY / CAROUSEL SECTION ======== --}}
<section class="py-16 md:py-24 bg-white">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
            <p class="text-[#448646] text-sm font-semibold uppercase tracking-wider mb-2">活動記録</p>
            <h2 class="text-3xl md:text-4xl font-extrabold text-[#296751]">Kegiatan Kami</h2>
        </div>

        {{-- Carousel — uses preserved carousel.css + carousel.js --}}
        <div class="carousel-container">
            <div class="carousel-wrapper" id="carouselWrapper">
                {{-- Carousel slides will be generated by JavaScript --}}
            </div>
            <button class="carousel-nav prev" id="prevBtn" aria-label="Previous slide">‹</button>
            <button class="carousel-nav next" id="nextBtn" aria-label="Next slide">›</button>
        </div>
        <div class="carousel-dots" id="carouselDots"></div>
    </div>
</section>

{{-- ======== LEARNING CARDS SECTION ======== --}}
<section id="belajar" class="py-16 md:py-24 bg-[#f8f7ef]">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-14">
            <p class="text-[#448646] text-sm font-semibold uppercase tracking-wider mb-2">経験すること</p>
            <h2 class="text-3xl md:text-4xl font-extrabold text-[#296751] mb-3">Keiken Suru Koto</h2>
            <p class="text-gray-500 text-lg">Apa yang akan kalian alami?</p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">

            {{-- Card 1: Budaya --}}
            <a href="#" class="group relative bg-white rounded-2xl p-6 shadow-sm hover:shadow-xl border border-gray-100 hover:border-[#448646]/30 transition-all duration-300 hover:-translate-y-2 overflow-hidden">
                <div class="absolute top-0 right-0 w-24 h-24 bg-[#448646]/5 rounded-full -translate-x-4 -translate-y-4 group-hover:scale-150 transition-transform duration-500"></div>
                <div class="relative z-10">
                    <div class="w-14 h-14 rounded-2xl bg-gradient-to-br from-[#448646]/10 to-[#296751]/10 flex items-center justify-center mb-5 group-hover:scale-110 transition-transform">
                        <span class="text-2xl font-bold text-[#448646]" style="font-family: 'Noto Sans JP', sans-serif;">あ</span>
                    </div>
                    <h3 class="text-lg font-bold text-[#296751] mb-2 group-hover:text-[#448646] transition-colors">Budaya Jepang</h3>
                    <p class="text-sm text-gray-500 leading-relaxed mb-4">
                        Memahami dan mengalami budaya Jepang melalui kebiasaan sederhana, interaksi, serta kegiatan yang dijalani bersama.
                    </p>
                    <span class="inline-flex items-center gap-1 text-sm font-semibold text-[#448646] group-hover:gap-2 transition-all">
                        Jelajahi <span class="text-lg">→</span>
                    </span>
                </div>
            </a>

            {{-- Card 2: Bahasa --}}
            <a href="{{ url('/bahasa') }}" class="group relative bg-white rounded-2xl p-6 shadow-sm hover:shadow-xl border border-gray-100 hover:border-[#448646]/30 transition-all duration-300 hover:-translate-y-2 overflow-hidden">
                <div class="absolute top-0 right-0 w-24 h-24 bg-[#d6975e]/5 rounded-full -translate-x-4 -translate-y-4 group-hover:scale-150 transition-transform duration-500"></div>
                <div class="relative z-10">
                    <div class="w-14 h-14 rounded-2xl bg-gradient-to-br from-[#d6975e]/10 to-[#b87a3a]/10 flex items-center justify-center mb-5 group-hover:scale-110 transition-transform">
                        <span class="text-2xl font-bold text-[#d6975e]" style="font-family: 'Noto Sans JP', sans-serif;">文</span>
                    </div>
                    <h3 class="text-lg font-bold text-[#296751] mb-2 group-hover:text-[#448646] transition-colors">Bahasa Jepang</h3>
                    <p class="text-sm text-gray-500 leading-relaxed mb-4">
                        Mempelajari bahasa Jepang secara bertahap dalam suasana yang santai dan antusias.
                    </p>
                    <span class="inline-flex items-center gap-1 text-sm font-semibold text-[#448646] group-hover:gap-2 transition-all">
                        Jelajahi <span class="text-lg">→</span>
                    </span>
                </div>
            </a>

            {{-- Card 3: Anime/Manga --}}
            <a href="#" class="group relative bg-white rounded-2xl p-6 shadow-sm hover:shadow-xl border border-gray-100 hover:border-[#448646]/30 transition-all duration-300 hover:-translate-y-2 overflow-hidden">
                <div class="absolute top-0 right-0 w-24 h-24 bg-[#4a7ec9]/5 rounded-full -translate-x-4 -translate-y-4 group-hover:scale-150 transition-transform duration-500"></div>
                <div class="relative z-10">
                    <div class="w-14 h-14 rounded-2xl bg-gradient-to-br from-[#4a7ec9]/10 to-[#3a6ab3]/10 flex items-center justify-center mb-5 group-hover:scale-110 transition-transform">
                        <span class="text-2xl font-bold text-[#4a7ec9]" style="font-family: 'Noto Sans JP', sans-serif;">語</span>
                    </div>
                    <h3 class="text-lg font-bold text-[#296751] mb-2 group-hover:text-[#448646] transition-colors">Anime, Manga & Game</h3>
                    <p class="text-sm text-gray-500 leading-relaxed mb-4">
                        Menikmati anime, manga, dan game sebagai ruang komunikasi, diskusi, serta memahami pesan yang diangkat.
                    </p>
                    <span class="inline-flex items-center gap-1 text-sm font-semibold text-[#448646] group-hover:gap-2 transition-all">
                        Jelajahi <span class="text-lg">→</span>
                    </span>
                </div>
            </a>

            {{-- Card 4: Kibun Tenkan --}}
            <a href="#" class="group relative bg-white rounded-2xl p-6 shadow-sm hover:shadow-xl border border-gray-100 hover:border-[#448646]/30 transition-all duration-300 hover:-translate-y-2 overflow-hidden">
                <div class="absolute top-0 right-0 w-24 h-24 bg-[#7c5cbf]/5 rounded-full -translate-x-4 -translate-y-4 group-hover:scale-150 transition-transform duration-500"></div>
                <div class="relative z-10">
                    <div class="w-14 h-14 rounded-2xl bg-gradient-to-br from-[#7c5cbf]/10 to-[#5e3da0]/10 flex items-center justify-center mb-5 group-hover:scale-110 transition-transform">
                        <span class="text-2xl font-bold text-[#7c5cbf]" style="font-family: 'Noto Sans JP', sans-serif;">話</span>
                    </div>
                    <h3 class="text-lg font-bold text-[#296751] mb-2 group-hover:text-[#448646] transition-colors">
                        Kibun Tenkan
                        <span class="block text-xs text-gray-400 font-normal mt-1" style="font-family: 'Noto Sans JP';">気分転換</span>
                    </h3>
                    <p class="text-sm text-gray-500 leading-relaxed mb-4">
                        Ruang untuk mengganti suasana, melepas penat kuliah, dan menikmati kebersamaan lewat kegiatan ringan.
                    </p>
                    <span class="inline-flex items-center gap-1 text-sm font-semibold text-[#448646] group-hover:gap-2 transition-all">
                        Jelajahi <span class="text-lg">→</span>
                    </span>
                </div>
            </a>

        </div>
    </div>
</section>

@endsection

@push('scripts')
<script src="{{ asset('js/carousel.js') }}"></script>
@endpush
